[2024-10-07 18:36:04,730] 161 numexpr.utils - INFO - NumExpr defaulting to 8 threads.
[2024-10-07 18:36:05,527] 69 root - INFO - >>>>> Nested Cross Validation Training Pipeline started <<<<
[2024-10-07 18:36:05,531] 26 root - INFO - yaml file: training/config/config.yaml loaded successfully as <class 'dict'>
[2024-10-07 18:36:05,532] 26 root - INFO - yaml file: training/config/params.yaml loaded successfully as <class 'dict'>
[2024-10-07 18:36:05,533] 26 root - INFO - yaml file: training/config/schema.yaml loaded successfully as <class 'dict'>
[2024-10-07 18:36:05,533] 43 root - INFO - Created directory at: artifacts
[2024-10-07 18:36:05,533] 43 root - INFO - Created directory at: artifacts/nested_cross_val
[2024-10-07 18:36:05,533] 43 root - INFO - Created directory at: artifacts/feature_extraction
[2024-10-07 18:36:05,533] 43 root - INFO - Created directory at: artifacts/nested_cross_val/random_search_models/random_forest
[2024-10-07 18:36:05,533] 43 root - INFO - Created directory at: artifacts/nested_cross_val/model_cache_rf
[2024-10-07 18:36:05,533] 43 root - INFO - Created directory at: artifacts/nested_cross_val/data_for_final_train
[2024-10-07 18:36:05,533] 43 root - INFO - Created directory at: artifacts/nested_cross_val/data_for_final_train
[2024-10-07 18:36:08,676] 82 root - INFO - Train.npz and Test.npz saved at artifacts/nested_cross_val/data_for_final_train and artifacts/nested_cross_val/data_for_final_train
[2024-10-07 18:36:24,314] 74 root - ERROR - Error occured in python script name [/content/Fabric_Detection/training/pipeline/cross_val/nested_cross_val.py] line number [53] error message[
All the 9 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 469, in fit
    Xt = self._fit(X, y, routed_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 406, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/usr/local/lib/python3.10/dist-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 1310, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_pca.py", line 474, in fit_transform
    U, S, _, X, x_is_centered, xp = self._fit(X)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_pca.py", line 547, in _fit
    return self._fit_full(X, n_components, xp, is_array_api_compliant)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_pca.py", line 561, in _fit_full
    raise ValueError(
ValueError: n_components=2510 must be between 0 and min(n_samples, n_features)=2495 with svd_solver='full'

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 469, in fit
    Xt = self._fit(X, y, routed_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 406, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/usr/local/lib/python3.10/dist-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 1310, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_pca.py", line 474, in fit_transform
    U, S, _, X, x_is_centered, xp = self._fit(X)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_pca.py", line 547, in _fit
    return self._fit_full(X, n_components, xp, is_array_api_compliant)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_pca.py", line 561, in _fit_full
    raise ValueError(
ValueError: n_components=2510 must be between 0 and min(n_samples, n_features)=2500 with svd_solver='full'
]
